### ISSUE TITLE
Allegro agent: errors due to read-only system readtable

### ISSUE THREAD

**Issue by metawilm** [cl-test-grid/cl-test-grid#25]
In Allegro the system readtable is read-only:
http://franz.com/support/tech_corner/sprs-of-interest-121410.lhtml

The puri library attempts to modify it, to enable this syntax: #u"http://example.com"
This gives a permanent build error:

<pre>
; Loading "puri"
; Fast loading
;    /home/cl-test-grid/lisp/cl-test-grid/work-dir/agent/test-runs/20150220212559-acl-9.0-linux-x86/fasl/ql/dists/quicklisp/software/puri-20101006-git/src.fasl
Unhandled SERIOUS-CONDITION of type COMMON-LISP:SIMPLE-ERROR is signaled:
 Attempt to set dispatch macro in system readtable #<readtable @ #x201089ca>; copy readtable first.
</pre>

In comparison, when Allegro starts interactively, the readtable in which the user commands are executed, is modifiable. Apparently other implementations have no problem with puri changing the standard readtable.

Could the Allegro agent command be modified, so that it executes:
 `(setf *readtable* (copy-readtable nil))`
before the loading of the library?

**Comment by avodonosov** [comment]
The read-only readtable breaks many libraries on allegro (in particular many puri dependencies).

But I doubt cl-test-grid must be modified - we collect results as is. If we `(ql:quickload :puri)` we have error, and we collect the error.

In other words, I think it's a bug either in puri to expect that current readtable can be modified and probably in Allegro which makes initial readtable read-only (CLHS says it is permissible for a program to modify initial redtable http://www.lispworks.com/documentation/lw51/CLHS/Body/02_aac.htm)

**Comment by avodonosov** [comment]
BTW, what prevents the fix of this issue is that puri author - Kevin Rosenberg - does not maintain it and doesn't respond emails. Probably someone could fork puri, fix the problem and ask Xach to use the fixed version in Quicklisp. But probably more important - there were no enough interest in this issue.

BTW, as of quicklisp 2013-01-28, puri was blocking 49 other projects: https://common-lisp.net/project/cl-test-grid/acl-load-failures.html

**Comment by metawilm** [comment]
I think the difference between unmodifiable "standard readtable" and modifiable "initial readtable" is relevant.

The agent starts Allegro using e.g. "-qq" which means no initialization is done (including leaving the standard readtable in place). Using that argument makes the agent directly responsible for making a sure a proper environment for loading the library is set up. As long as libraries (in that page also iolib.base) assume they can modify the (initial) readtable, which is okay with the CLHS, the agent should support that by providing a modifiable initial readtable.

So I think the agent has a responsible here, whether or not it's a good idea for a library to change the readtable at time of loading.

**Comment by avodonosov** [comment]
> The agent starts Allegro using e.g. "-qq" which means no initialization is done (including leaving the standard readtable in place). 

No, -qq does not mean "leave standard readtable in place". There is no such rule that `*readtable*` is first initialized to standard unmodifiable readtable, and only later, in context of some initialization is changed to initial readtable.

CLHS does not guaranty that the current value of `*readtable*` is a modifiable readtable, and libraries assuming that are buggy.

**Comment by metawilm** [comment]
OK, I agree with you.
