### ISSUE TITLE
Broken link in readme for ECL load failures

### ISSUE THREAD

**Issue by dkochmanski** [cl-test-grid/cl-test-grid#28]
Now trying to get familiar with cl-test-grid, and this particular link didn't work:
https://common-lisp.net/project/cl-test-grid/ecl-load-failures.html

**Comment by avodonosov** [comment]
Thanks for the report, the correct links are:
https://common-lisp.net/project/cl-test-grid/ecl-load-failures-bytecode.html
https://common-lisp.net/project/cl-test-grid/ecl-load-failures-lisp-to-c.html

Let me know if you need any assistance with cl-test-grid or new reports.
