### ISSUE TITLE
Help request: describing external-symbol-not-found conditions

### ISSUE THREAD

**Issue by phoe** [cl-test-grid/cl-test-grid#35]
I am trying to develop a Common Lisp type named `EXTERNAL-SYMBOL-NOT-FOUND` that is going to match all conditions which are signaled when the reader attempts to access a non-existing external symbol of a package.

Example:
```lisp
(make-package 'foo :use nil)
(read-from-string "foo:bar")
```

Because different implementations implement this differently, I will most likely have to use `SATISFIES` in some cases, for example in CCL.

In order to be able to efficiently implement this function, I need to be able to run the following snippet of code on as many implementations as possible, so I know what I should be looking for inside conditions for a given implementation.

```lisp
(handler-case (progn
                (unless (find-package 'temp)
                  (make-package 'temp :use nil))
                (read-from-string "temp:symbol"))
  (error (e)
    (fresh-line)
    (format t "~A~%" e)
    (describe e)
    (describe (class-of e))))
```

Are you able to help me with this?

**Comment by avodonosov** [comment]
@phoe , sorry for the silence. I think I saw this ticket opened, and hoped to answer later, but then forgot.

Should I keep it open or you found a solution?

**Comment by phoe** [comment]
Goodness, I forgot about it!

I found a solution to run the code on many implementations - thank you.

**Comment by avodonosov** [comment]
How did you do it? Manuanly, roswell, or something else?

**Comment by phoe** [comment]
I managed to install all the implementations except for Clasp, some with the help of Roswell and some not. Then it's all manual work.
