### ISSUE TITLE
[question] How would I specify a version of ASDF to use in the tests?

### ISSUE THREAD

**Issue by rpgoldman** [cl-test-grid/cl-test-grid#41]
I'd like to see what effects a particular ASDF version (in my case a patch I consider merging) would have on the Quicklisp libraries.

So is there some easy way to modify tests so that I can supply a specific asdf.lisp file location?

Thank you!

**Comment by avodonosov** [comment]
To test ASDF I create a download quicklisp to a separate folder, place new asdf.lisp file, remove the compiled asdf fasl files. Then edit quicklisp/setup.lisp file: change the *required-asdf-version* value:
```common-lisp
;my:
;(defvar *required-asdf-version* "2.26")
(defvar *required-asdf-version* "3.3.1.3")
```
And then, in cl-test-grid's run-agent.lisp, in addition to usual setup I do:

```common-lisp

(setf (test-grid-agent::result-storage-name *agent*) "asdf")

```
And instead of running `(tg-agent:main *agent*)`

```common-lisp
  (test-grid-agent::test-patched-quicklisp *agent*
                                            #p"/home/testgrid/quicklisp-asdf3/"
                                            "quicklisp 2018-02-28 + asdf.syntax-ctrl.8dc0778")
```

The second argument here is the path to the customized quicklisp directory, and the third argument is the lib-world name.

If you want, I can run tests for your version of ASDF on the lisp implementations that I have on cl-test-grid.cloud.efficito.com machine. I will have some time for that in the coming days.

You can see here the lisps I have currently installed: https://cl-test-grid.common-lisp.dev/library/alexandria.html

**Comment by rpgoldman** [comment]
Thank you @avodonosov !

I will get a longer answer to you later, but if you have a chance to run tests on ASDF, it would be great if you could compare tag `3.3.5.7` with branch `uiop-docstring`

**Comment by avodonosov** [comment]
With upgrade from the implementation-provided ASDF or without upgrade?

**Comment by rpgoldman** [comment]
Maybe it would be best to just load the new one directly?

I’m mostly concerned with anything a bug fix might break, so testing the upgrade would be a separate question. That is a lot simpler and we can do it on common-lisp.net

Thank you again, and have a good weekend!

**Comment by avodonosov** [comment]
I started to work on this, but with ASDf 3.3.5.7 my code fails at this line: https://github.com/cl-test-grid/cl-test-grid/blob/master/agent/proc-common-asdf.lisp#L51

Because there is no `asdf::defun*` anymore. I will need to study how to solve this.

**Comment by rpgoldman** [comment]
`defun*` was removed in 2020.  See [this ASDF commit](https://gitlab.common-lisp.net/asdf/asdf/-/commit/32a579df0e942ab7a71a40250f26c171b405d8be) and [this one for the actual removal of the definitions of `defgeneric*` and `defun*`](https://gitlab.common-lisp.net/asdf/asdf/-/commit/3bb042cba79176e99db2312f5be65f090c5e0e94).

According to the comments, this is what `defun*` used to do:

```
;; DEFUN* and DEFGENERIC* use FMAKUNBOUND to delete any previous fdefinition,
;; thus replacing the function without warning or error
;; even if the signature and/or generic-ness of the function has changed.
;; For a generic function, this invalidates any previous DEFMETHOD.
```

In one location, I see:

```
  (defun* (normalize-version) (form &key pathname component parent)
```

replaced by:

```
  (fmakunbound 'normalize-version) ;; signature changed between 2.27 and 2.31
  (defun normalize-version ...
```

**Comment by rpgoldman** [comment]
I don't know if this also involves ensuring that these functions are `notinline`.

**Comment by avodonosov** [comment]
Fixed that - for new ASDF I utilize the `uiop:*output-translation-function*`, which wasn't established yet when I created the old version of this code.

Currntly the tests for ADSF 3.3.5.7 on SBCL 1.3.21 and CCL 1.11.5.

**Comment by avodonosov** [comment]
No regressions found for these two lisps when using ASDF bransh uiop-docstring, commit 6ba0224. Neither comparing to ASDF 3.3.5.7 nor to the default ASDF coming with those lisps and Quicklisp.

Now running the tests for other lisps I have.

**Comment by avodonosov** [comment]
Update.

The tests are still running. So far have completed these lisps on ASDF branch uiop-docstring, commit 6ba0224.

abcl-1.8.0-fasl43-linux-x86
acl-10.1s-linux-x86
ccl-1.11-5-rv1.11.5-f96-linux-x86
clisp-2.49.92-unix-x86
cmu-snapshot-2016-12__21b_unicode_-linux-x86
ecl-16.1.2-unknown-linux-x86-bytecode
ecl-16.1.2-unknown-linux-x86-lisp-to-c
sbcl-1.3.21-linux-x86

So far,  when comparing the results to the ones I have for the default ASDF coming with those lisps, I see no problems that could be attributed to ASDF change.

I want also to complete tests specifically for ASDF 3.3.5.7 and compare - it will give me less noise to filter out in the comparison results.

Will update when ready.

**Comment by avodonosov** [comment]
@rpgoldman , after comparing test results with ASDF 3.3.5.7 and ASDF branch uiop-docstring, commit 6ba0224, on the following lisps:

abcl-1.8.0-fasl43-linux-x86
acl-10.1ms-linux-x86
acl-10.1s-linux-x86
ccl-1.10-r16196-f96-linux-x86
ccl-1.11-5-rv1.11.5-f96-linux-x86
clisp-2.49.92-unix-x86
cmu-snapshot-2016-12__21b_unicode_-linux-x86
ecl-16.1.2-unknown-linux-x86-bytecode
ecl-16.1.2-unknown-linux-x86-lisp-to-c
sbcl-1.1.16-linux-x86
sbcl-1.2.6-linux-x86
sbcl-1.3.12-linux-x86
sbcl-1.3.17-linux-x86
sbcl-1.3.20-linux-x86
sbcl-1.3.21-linux-x86

I see no errors that could be attributed to ASDF.
