### ISSUE TITLE
LANG environment variable?

### ISSUE THREAD

**Issue by nklein** [cl-test-grid/cl-test-grid#6]
To run cl-test-grid under MacOSX, I made a new user to run it with to ensure that none of my settings got in the way.  In this new user's environment, I forgot to set the LANG environment variable.  This meant that a variety of tests failed when the lisps tried to load packages that used a non-ASCII coding.

Arguably, this could be considered a bug either in the source code that used non-ASCII, the compiler that defaulted to ASCII rather than UTF-8 in the absence of any indication, user error for not setting the LANG environment variable to something UTF-8, or the run.sh script.

Anyhow, if you think run.sh should set LANG to en_US.UTF-8 or some such thing, then cool.  Otherwise, just consider this notification that many of the "fail" reports that I sent in the last few days were an error in my runtime environment, not in the lisp implementations or the libraries.

-- pat@nklein.com

**Comment by attila-lendvai** [comment]
i also think that forcing cl-test-grid to utf-8 would make it more useful.

IOW, more projects will break due to *not* using utf-8 than due to using it. and using it is the way to go, so maybe cl-test-grid results could be a nice indicator of those mythical libraries...

**Comment by avodonosov** [comment]
I thought about this issue several times and I'm sure cl-test-grid should not force utf-8.
The job of cl-test-grid is to detect bugs and problems, and when a system uses non-ascii characters without specifying encoding explicitly is deficient. We detect this problem and author can fix it.

**Comment by attila-lendvai** [comment]
err, sorry, i didn't see the whole picture... i saw all these encoding errors in the cl-test-grid output for our hu.dwim libs, but i only now realized that they are due to old lisp and/or asdf versions, and newer versions work fine.

**Comment by avodonosov** [comment]
Thanks for the message anyway.

If you want your systems to use UTF-8 even in old ASDF, do like this: http://cliki.net/ASDF%20encoding
